using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UniRx;
using System;
using Cysharp.Threading.Tasks;
using DG.Tweening;
using UnityEngine.UI;
using MoreMountains.Feedbacks;
using TMPro;
using UnityEngine.Serialization;

public class TimingManager : MonoBehaviour
{
    [Header("ï¿½nï¿½_ï¿½ï¿½ï¿½ï¿½Iï¿½_ï¿½Ü‚Å‚Ìï¿½ï¿½ÔAï¿½Xï¿½Nï¿½ï¿½ï¿½vï¿½gï¿½ï¿½ï¿½ï¿½Ì•ÏXï¿½ï¿½ï¿½Â”")]
    public float second;
    [Header("Maxï¿½ï¿½ï¿½ï¿½,Minï¿½ï¿½ï¿½ï¿½")]
    private float MAX = 4f;
    private float MIN = 1.0f;
    float ChangeTime = 0.3f;

    [SerializeField, Header("ï¿½ï¿½ï¿½_ï¿½Íˆï¿½(ï¿½ï¿½ ï¿½ï¿½ ï¿½Sï¿½ï¿½ ï¿½~ ï¿½ï¿½ï¿½ï¿½ï¿½Aï¿½ï¿½ ï¿½ï¿½ ï¿½Î‚Ì”Íˆï¿½ ï¿½~ ï¿½ï¿½ï¿½ï¿½)")]
    private AllRange range;

    [SerializeField]
    private TargetAreaManager targetAreaManager;
    [SerializeField]
    private CursorController cursorController;

    [SerializeField] private GameObject cursorPoint;
    [SerializeField] private TextMeshProUGUI justText, goodText;
    [SerializeField] private GameObject slider;

    // ï¿½Oï¿½Ì‚ï¿½ï¿½ß—pï¿½Ó‚ï¿½ï¿½ï¿½ï¿½Ì‚ÅAï¿½Vï¿½[ï¿½ï¿½ï¿½Jï¿½Ú‚ï¿½ï¿½éï¿½Æ‚ï¿½ï¿½ï¿½Disposeï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½B
    private IDisposable rangeDispose;
    private IDisposable secondDispose;

    [SerializeField, Header("ï¿½ï¿½ï¿½ï¿½ï¿½lï¿½mï¿½Fï¿½pï¿½Aï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½İ‹Ö~")]
    private Timing timing;

    [SerializeField, Header("ï¿½fï¿½oï¿½bï¿½Oï¿½pï¿½Aï¿½Kï¿½vï¿½È‚ï¿½ï¿½È‚ï¿½Îï¿½ï¿½ï¿½")]
    private Button btn;

    private Coroutine cursorCoroutine;

    private bool isRunning = false;

    public MMFeedbacks redFeedback;

    [FormerlySerializedAs("SE")] [SerializeField] private AudioSource justSE;
    [SerializeField] private AudioSource goodSE;

    private bool isSlideAnimation = false;

    /// <summary>
    /// ï¿½ï¿½ï¿½_ï¿½ÍˆÍ‚ï¿½Ï‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ‚ï¿½ï¿½Égï¿½ï¿½ï¿½Öï¿½
    /// ï¿½ÎƒGï¿½ï¿½ï¿½Aï¿½Ìnï¿½_ï¿½ÆIï¿½_ï¿½Aï¿½ÔƒGï¿½ï¿½ï¿½Aï¿½Ìnï¿½_ï¿½ÆIï¿½_ï¿½ÌŒv4ï¿½Â‚ï¿½ï¿½wï¿½è‚·ï¿½ï¿½
    /// </summary>
    /// <param name="newRange"></param>
    public void SetNewRange(AllRange newRange)
    {
        range.green = newRange.green;
        range.red = newRange.red;
    }
    
    /// <summary>
    /// ï¿½ï¿½ï¿½_ï¿½ï¿½ï¿½Ô‚ï¿½ï¿½vï¿½Z
    /// </summary>
    /// <param name="nowRange"></param>
    private void SetNewTiming(AllRange nowRange)
    {
        timing.greenStart = second * nowRange.green.left;
        timing.greenEnd = second * nowRange.green.right;
        timing.redStart = timing.greenStart + (timing.greenEnd - timing.greenStart) * nowRange.red.left;
        timing.redEnd = timing.greenStart + (timing.greenEnd - timing.greenStart) * nowRange.red.right;
    }

    /// <summary>
    /// ï¿½^ï¿½Cï¿½~ï¿½ï¿½ï¿½Oï¿½Qï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½nï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    /// </summary>
    public void CursorStart()
    {
        cursorCoroutine = StartCoroutine(cursorController.CursorMove(second));
        isRunning = true;
    }

    public void CursorStop()
    {
        try
        {
            StopCoroutine(cursorCoroutine);
        }
        catch
        {

        }
    }

    private void Start()
    {
        rangeDispose = gameObject.ObserveEveryValueChanged(_ => range) // ï¿½ï¿½ï¿½_ï¿½ÍˆÍ‚ï¿½ï¿½ÏXï¿½ï¿½ï¿½ê‚½ï¿½Æ‚ï¿½UIï¿½Ì’ï¿½ï¿½ï¿½ï¿½Æ“ï¿½ï¿½_ï¿½ï¿½ï¿½Ô‚ÌŒvï¿½Zï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            .Subscribe(_ =>
            {
                targetAreaManager.SetRange(range);
                SetNewTiming(range);
            }).AddTo(this);

        secondDispose = gameObject.ObserveEveryValueChanged(_ => second) // ï¿½nï¿½_ï¿½ï¿½ï¿½ï¿½Iï¿½_ï¿½Ü‚Å‚Ìï¿½ï¿½Ô‚ï¿½ï¿½ÏXï¿½ï¿½ï¿½ê‚½ï¿½Æ‚ï¿½ï¿½ï¿½ï¿½_ï¿½ï¿½ï¿½Ô‚ï¿½ï¿½vï¿½Zï¿½ï¿½ï¿½ï¿½
            .Subscribe(_ =>
            {
                SetNewTiming(range);
            }).AddTo(this);

        SetNewRange(range); // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½

        second = 2.5f;

        TimeManager.instance.time
            .Subscribe(x =>
            {
                if (x == 18)
                {
                    MIN = 0.8f;
                    //Debug.Log("MINæ›´æ–°");
                    range.green.left = 0.55f;
                    range.green.right = 0.95f;
                    SetNewRange(range);
                }

                if (x == 12)
                {
                    MIN = 0.6f;
                    //Debug.Log("MINæ›´æ–°");
                    // range.red.left = 0.2f;
                    // range.green.left = 0.5f;
                    // range.red.right = 0.8f;
                    // SetNewRange(range);
                }

                if (x == 7)
                {
                    MIN = 0.5f;
                    //Debug.Log("MINæ›´æ–°");
                    range.green.left = 0.3f;
                    range.red.left = 0.5f;
                    range.red.right = 0.75f;
                    SetNewRange(range);
                }

                if (x == 2)
                {
                    MIN = 0.7f;
                    second = 0.7f;
                    //Debug.Log("MINæ›´æ–°");
                    range.green.left = 0f;
                    range.green.right = 1f;
                    range.red.left = 0f;
                    range.red.right = 1f;
                    SetNewRange(range);
                }

                if (x == 0)
                {
                    Debug.Log("çµ‚äº†");
                    CursorStop();
                    isRunning = false;
                }
            });

        justText.DOFade(0f, 0f);
        goodText.DOFade(0, 0);
        
        //ä»®
        // IsRunningOn(3);
    }

    /// <summary>
    /// ï¿½ï¿½ï¿½_ï¿½vï¿½Zï¿½Öï¿½
    /// </summary>
    /// <param name="time"></param>
    public void CheckTiming(double time) // ï¿½ï¿½ï¿½ï¿½Debug.Log()ï¿½ğ—¬‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½È‚Ì‚ÅAï¿½ï¿½ï¿½_ï¿½ÌƒVï¿½Xï¿½eï¿½ï¿½ï¿½ï¿½ï¿½Å‚ï¿½ï¿½ï¿½ï¿½ç‚»ï¿½ï¿½É’uï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½B
    {
        ChangeTime = second > 1.0f ? 0.3f : 0.1f;
        if (time < timing.greenStart)
        {
            //Debug.Log("é…ã„");
            second = Mathf.Clamp(second + ChangeTime, MIN, MAX);
            ScoreManager.instance.combo.Value = 0;
        }
        else if ((time >= timing.greenStart) && (time < timing.redStart))
        {
            //Debug.Log("ã¡ã‚‡ã£ã¨é…ã„");
            ScoreManager.instance.AddScore(60);
            DispText(goodText);
            goodSE.Play();
            ScoreManager.instance.ScoreTextAnimation();
            ScoreManager.instance.combo.Value = 0;
        }
        else if ((time >= timing.redStart) && (time <= timing.redEnd))
        {
            //Debug.Log("ã´ã£ãŸã‚Š");
            second = Mathf.Clamp(second - ChangeTime, MIN, MAX);
            ScoreManager.instance.AddScore(125);
            PlayRedFeedback();
            justSE.Play();
            if (!isSlideAnimation)
            {
                isSlideAnimation = true;
                slider.transform.DOPunchScale(new Vector3(0.1f, 0.1f, 0), 0.2f)
                    .OnComplete(() =>
                    {
                        isSlideAnimation = false;
                    });
            }
            DispText(justText);
            ScoreManager.instance.ScoreTextAnimation();
            ScoreManager.instance.combo.Value++;
        }
        else if ((time > timing.redEnd) && (time <= timing.greenEnd))
        {
            //Debug.Log("ã¡ã‚‡ã£ã¨æ—©ã„");
            ScoreManager.instance.AddScore(60);
            DispText(goodText);
            goodSE.Play();
            ScoreManager.instance.ScoreTextAnimation();
            ScoreManager.instance.combo.Value = 0;
        }
        else if ((time > timing.greenEnd) && (time <= second))
        {
            //Debug.Log("æ—©ã„");
            second = Mathf.Clamp(second + ChangeTime, MIN, MAX);
            ScoreManager.instance.combo.Value = 0;
        }
        else if (time > second)
        {
            //Debug.Log("è¡ŒãéããŸ");
            second = Mathf.Clamp(second + ChangeTime, MIN, MAX);
            ScoreManager.instance.combo.Value = 0;
        }
        // Debug.Log("ï¿½ï¿½ï¿½ï¿½ : " + time + "ï¿½b");
        CursorStart();
        //btn.interactable = true; //ï¿½fï¿½oï¿½bï¿½Oï¿½pï¿½Aï¿½Kï¿½vï¿½È‚ï¿½ï¿½È‚ï¿½Îï¿½ï¿½ï¿½ï¿½B
    }

    private void Update()
    {
        if(!isRunning) return;
        
        ScoreManager.instance.AddScore(100/Mathf.Pow(second, 2) * Time.deltaTime);
    }

    private async void IsRunningOn(int time)
    {
        await UniTask.Delay(TimeSpan.FromSeconds(time));
        Debug.Log("isRunningON");
        isRunning = true;
    }

    private void PlayRedFeedback()
    {
        redFeedback?.PlayFeedbacks();
    }

    private void DispText(TextMeshProUGUI text)
    {
        text.transform.DOMoveX(cursorPoint.transform.position.x, 0);
        text.DOFade(0, 0);
        text.transform.DOScale(new Vector3(1, 1, 1), 0);
        text.DOFade(1, 0.3f);
        text.transform.DOScale(new Vector3(2, 2, 2), 0.3f)
            .OnComplete(() =>
            {
                text.DOFade(0, 0.2f);
            });
    }
}

[System.Serializable]
public struct AllRange
{
    public Range green;
    public Range red;
}

[System.Serializable]
public struct Range
{
    [Range(0,1)]
    public float left;
    [Range(0,1)]
    public float right;
}

[System.Serializable]
public struct Timing
{
    public float greenStart;
    public float redStart;
    public float redEnd;
    public float greenEnd;
}
